name: Code Formatting

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Install C++ build dependencies
        run: brew install clang-format

      - name: Run Black (Python Formatter)
        run: black --check .

      - name: Run Flake8 (Python Linter)
        run: flake8 --exclude=.venv,build .

      - name: Run ClangFormat (C++ Formatter)
        run: find core -type f \( -name "*.cpp" -o -name "*.h" \) -exec clang-format -i {} +
